version: '3.7'

services:
  nginx:
      image: nginx
      restart: on-failure
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/log/:/var/log/nginx/
        - ./nginx/cache/:/var/cache/nginx/
      networks:
        - task_26_net
      depends_on:
        - fastapi
        - golang
  fastapi:
    build:
      context: ./fastapi
      dockerfile: dockerfile
    restart: on-failure
    hostname: fastapi
    networks:
      - task_26_net
  golang:
    build:
      context: ./golang
      dockerfile: dockerfile
    restart: on-failure
    hostname: golang
    networks:
      - task_26_net
networks:
  task_26_net: