---
- name: Add garafana repo
  template:
    dest: /etc/yum.repos.d/grafana.repo
    src: templates/grafana.repo.j2

- name: Install grafana
  yum:
    name: grafana
    state: present
  notify: 
    - daemon reload
    - start grafana 

- name: Copy grafana db with dashboard
  copy:
    src: 'grafana.db'
    dest: '/var/lib/grafana/'
