---
- name: Install epel-release
  yum:
    name:
      - epel-release
    state: present

- name: Add ELK Repo
  yum_repository:
    name: elasticsearch
    file: elasticsearch
    description: Elasticsearch repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: no
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    repo_gpgcheck: no

- name: Install packages
  yum:
    name:
      - filebeat
      - nginx
      - audit
    state: present
  notify:
    - Enable Services

- name: Add configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'filebeat.yml', dest: '/etc/filebeat/filebeat.yml'} 
  notify:
    - Restart Services

- name: Enable filebeat modules
  command:
    filebeat modules enable nginx system auditd

- name: Add audit rules
  command:
    auditctl -w /etc/nginx/nginx.conf -p wa -k nginx_config_changed
...