---
- name: Enable Services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - filebeat
    - nginx

- name: Restart Services
  service:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  with_items:
    - filebeat
    - nginx
...