---
# tasks file for roles/nginx
- name: Install Epel Repo
  yum:
     name: epel-release
     state: present

- name: "Install Nginx"
  yum:
    name: "{{ nginx_vars.package }}"
    state: present 
  notify:
    - start nginx

- name: "Config nginx"
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart nginx
...