---
# handlers file for roles/nginx
- name: start nginx
  systemd:
    name: "{{ nginx_vars.package }}"
    state: started
    enabled: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
...